# Generated by Django 4.2.7 on 2025-09-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المشروع')),
                ('description', models.TextField(verbose_name='وصف المشروع')),
                ('project_type', models.CharField(choices=[('marketing_strategy', 'استراتيجية تسويقية'), ('brand_identity', 'هوية تجارية'), ('digital_marketing', 'تسويق رقمي'), ('social_media', 'وسائل التواصل الاجتماعي'), ('website_development', 'تطوير موقع إلكتروني'), ('content_creation', 'إنتاج محتوى'), ('consultation', 'استشارة'), ('other', 'أخرى')], max_length=50, verbose_name='نوع المشروع')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشط'), ('on_hold', 'معلق'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='حالة المشروع')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='الموعد النهائي')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الميزانية')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='التكلفة الفعلية')),
                ('requirements', models.TextField(blank=True, verbose_name='المتطلبات')),
                ('deliverables', models.TextField(blank=True, verbose_name='المخرجات المطلوبة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('project_folder', models.CharField(blank=True, max_length=500, verbose_name='مجلد المشروع')),
                ('is_confidential', models.BooleanField(default=False, verbose_name='سري')),
                ('client_can_view_progress', models.BooleanField(default=True, verbose_name='يمكن للعميل رؤية التقدم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('is_internal', models.BooleanField(default=False, help_text='لا يراه العميل', verbose_name='داخلي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تعليق',
                'verbose_name_plural': 'التعليقات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('file', models.FileField(upload_to='projects/files/', verbose_name='الملف')),
                ('file_type', models.CharField(choices=[('document', 'مستند'), ('image', 'صورة'), ('video', 'فيديو'), ('audio', 'صوت'), ('archive', 'أرشيف'), ('other', 'أخرى')], default='document', max_length=20, verbose_name='نوع الملف')),
                ('file_size', models.PositiveIntegerField(help_text='بالبايت', verbose_name='حجم الملف')),
                ('description', models.TextField(blank=True, verbose_name='وصف الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('is_public', models.BooleanField(default=False, help_text='يمكن للعميل رؤيته', verbose_name='عام')),
            ],
            options={
                'verbose_name': 'ملف مشروع',
                'verbose_name_plural': 'ملفات المشاريع',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'مدير'), ('developer', 'مطور'), ('designer', 'مصمم'), ('content_creator', 'منشئ محتوى'), ('analyst', 'محلل'), ('coordinator', 'منسق')], max_length=50, verbose_name='الدور')),
                ('can_edit_project', models.BooleanField(default=False, verbose_name='يمكن تعديل المشروع')),
                ('can_manage_tasks', models.BooleanField(default=True, verbose_name='يمكن إدارة المهام')),
                ('can_view_financials', models.BooleanField(default=False, verbose_name='يمكن رؤية المعلومات المالية')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
            ],
            options={
                'verbose_name': 'عضو فريق المشروع',
                'verbose_name_plural': 'أعضاء فريق المشروع',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المهمة')),
                ('description', models.TextField(blank=True, verbose_name='وصف المهمة')),
                ('status', models.CharField(choices=[('todo', 'قائمة المهام'), ('in_progress', 'قيد التنفيذ'), ('review', 'قيد المراجعة'), ('completed', 'مكتملة'), ('cancelled', 'ملغية')], default='todo', max_length=20, verbose_name='حالة المهمة')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='الساعات المقدرة')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='الساعات الفعلية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مهمة',
                'verbose_name_plural': 'المهام',
                'ordering': ['-created_at'],
            },
        ),
    ]
