# Generated by Django 4.2.7 on 2025-09-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=100, verbose_name='الاسم الأخير')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('company_name', models.CharField(max_length=200, verbose_name='اسم الشركة')),
                ('company_registration', models.CharField(blank=True, max_length=100, verbose_name='رقم السجل التجاري')),
                ('tax_number', models.CharField(blank=True, max_length=100, verbose_name='الرقم الضريبي')),
                ('company_website', models.URLField(blank=True, verbose_name='موقع الشركة')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='الصناعة')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='الدولة')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='الرمز البريدي')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('suspended', 'معلق'), ('terminated', 'منتهي')], default='active', max_length=20, verbose_name='الحالة')),
                ('client_since', models.DateField(auto_now_add=True, verbose_name='عميل منذ')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الحد الائتماني')),
                ('payment_terms', models.CharField(blank=True, max_length=100, verbose_name='شروط الدفع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=100, verbose_name='الاسم الأخير')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الشركة')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='المسمى الوظيفي')),
                ('company_website', models.URLField(blank=True, verbose_name='موقع الشركة')),
                ('company_size', models.CharField(blank=True, max_length=50, verbose_name='حجم الشركة')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='الصناعة')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('contacted', 'تم التواصل'), ('qualified', 'مؤهل'), ('proposal_sent', 'تم إرسال العرض'), ('negotiation', 'تفاوض'), ('won', 'تم الفوز'), ('lost', 'خسارة'), ('cancelled', 'ملغي')], default='new', max_length=20, verbose_name='الحالة')),
                ('source', models.CharField(choices=[('website', 'الموقع الإلكتروني'), ('social_media', 'وسائل التواصل الاجتماعي'), ('referral', 'إحالة'), ('cold_call', 'اتصال بارد'), ('email_campaign', 'حملة بريد إلكتروني'), ('event', 'فعالية'), ('advertisement', 'إعلان'), ('other', 'أخرى')], max_length=20, verbose_name='المصدر')),
                ('interested_services', models.TextField(blank=True, verbose_name='الخدمات المهتم بها')),
                ('budget_range', models.CharField(blank=True, max_length=100, verbose_name='نطاق الميزانية')),
                ('timeline', models.CharField(blank=True, max_length=100, verbose_name='الجدول الزمني')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('last_contact_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ آخر تواصل')),
                ('next_follow_up', models.DateTimeField(blank=True, null=True, verbose_name='موعد المتابعة التالية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'عميل محتمل',
                'verbose_name_plural': 'العملاء المحتملون',
                'ordering': ['-created_at'],
            },
        ),
    ]
